// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/dayronmiranda/claude-monitor",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/dayronmiranda/claude-monitor/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/cache": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna el estado actual del cache de analytics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Obtener estado del cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/analytics/global": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna estadísticas globales de todos los proyectos y sesiones",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Obtener analytics globales",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Forzar recálculo (default: false)",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.GlobalAnalytics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/analytics/invalidate": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Invalida el cache de analytics para un session-root o globalmente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Invalidar cache de analytics",
                "parameters": [
                    {
                        "description": "Session-root a invalidar (vacío = global)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_root": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/analytics/session-roots/{rootPath}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna estadísticas detalladas de un session-root específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Obtener analytics de session-root",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Forzar recálculo (default: false)",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ProjectAnalytics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/filesystem/dir": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Lista el contenido de un directorio del filesystem (restringido a paths permitidos)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filesystem"
                ],
                "summary": "Listar directorio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del directorio (default: /)",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Retorna el estado de salud del servicio con checks de filesystem, memoria, goroutines y terminales",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "Health check del servicio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/host": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna información del servidor incluyendo versión, plataforma y estadísticas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "Obtener información del host",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.HostInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Verifica si el servicio está listo para recibir tráfico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "Readiness probe para Kubernetes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/session-roots": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna todos los directorios donde se han ejecutado sesiones de Claude",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-roots"
                ],
                "summary": "Listar session-roots",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna información detallada de un session-root incluyendo estadísticas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-roots"
                ],
                "summary": "Obtener session-root",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Elimina un session-root y todas sus sesiones",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-roots"
                ],
                "summary": "Eliminar session-root",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/activity": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna la actividad diaria/semanal del session-root",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session-roots"
                ],
                "summary": "Obtener actividad de session-root",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna todas las sesiones de Claude en un session-root",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Listar sesiones",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/clean": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Elimina todas las sesiones sin mensajes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Limpiar sesiones vacías",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/delete": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Elimina varias sesiones a la vez",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Eliminar múltiples sesiones",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "IDs de sesiones a eliminar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_ids": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/import": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Marca una sesión para que aparezca en la lista de terminales guardadas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Importar sesión a terminales",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de importación",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "session_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/{sessionID}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna información detallada de una sesión específica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Obtener sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ClaudeSession"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Elimina una sesión y sus mensajes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Eliminar sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/{sessionID}/messages": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna todos los mensajes de una sesión",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Obtener mensajes de sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/{sessionID}/messages/realtime": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna mensajes nuevos desde una línea específica (para polling)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Obtener mensajes en tiempo real",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Línea desde donde obtener mensajes (default: 0)",
                        "name": "from",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/{sessionID}/move": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Mueve una sesión a otro directorio, actualizando todas las rutas internas del JSONL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Mover sesión a otro directorio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root actual (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva ruta absoluta del proyecto",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "new_path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.MoveSessionResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/session-roots/{rootPath}/sessions/{sessionID}/rename": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Cambia el nombre personalizado de una sesión",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Renombrar sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Path del session-root (URL encoded)",
                        "name": "rootPath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de la sesión",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo nombre",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ClaudeSession"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna lista de todas las terminales activas y guardadas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Listar terminales",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Crea una nueva terminal PTY (tipo claude o terminal estándar)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Crear terminal",
                "parameters": [
                    {
                        "description": "Configuración de terminal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.TerminalConfig"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.TerminalInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna información de una terminal específica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.TerminalInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Elimina una terminal guardada (no activa)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Eliminar terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/archive": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Archiva una terminal Claude detenida o pausada (solo terminales tipo claude)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Archivar terminal Claude",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/checkpoints": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna los checkpoints/puntos de control del agente Claude",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener checkpoints de Claude",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/claude-state": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna el estado actual del agente Claude en la terminal (solo terminales tipo claude)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener estado de Claude",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/events": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna los eventos del agente Claude (tool calls, respuestas, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener eventos de Claude",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/kill": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Termina forzosamente una terminal activa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Matar terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/messages": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna contadores de mensajes de una terminal Claude (message_count, user_messages, assistant_messages)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener métricas de mensajes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/pause": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Pausa una terminal Claude activa (solo terminales tipo claude)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Pausar terminal Claude",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/resize": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Cambia el tamaño de una terminal activa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Redimensionar terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevas dimensiones",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cols": {
                                    "type": "integer"
                                },
                                "rows": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/resume": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Reanuda una terminal guardada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Reanudar terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.TerminalInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/snapshot": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna el estado actual de la pantalla de la terminal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener snapshot de terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/state": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retorna el estado de la máquina de estados de una terminal Claude (created, active, paused, stopped, archived, error)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Obtener estado de máquina de estados",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ClaudeStateSnapshot"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/unpause": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Reanuda una terminal Claude que está pausada (diferente de Resume que recrea la terminal)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Reanudar terminal Claude pausada",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIResponse"
                        }
                    }
                }
            }
        },
        "/terminals/{terminalID}/ws": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Establece conexión WebSocket para interactuar con la terminal en tiempo real",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminals"
                ],
                "summary": "Conectar WebSocket a terminal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la terminal",
                        "name": "terminalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/errors.ErrorCode"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "errors.ErrorCode": {
            "type": "string",
            "enum": [
                "NOT_FOUND",
                "INVALID_INPUT",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "INTERNAL_ERROR",
                "CONFLICT",
                "BAD_REQUEST",
                "PATH_NOT_ALLOWED",
                "TOO_MANY_REQUESTS"
            ],
            "x-enum-varnames": [
                "ErrCodeNotFound",
                "ErrCodeInvalidInput",
                "ErrCodeUnauthorized",
                "ErrCodeForbidden",
                "ErrCodeInternal",
                "ErrCodeConflict",
                "ErrCodeBadRequest",
                "ErrCodePathNotAllowed",
                "ErrCodeTooManyRequests"
            ]
        },
        "handlers.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/errors.APIError"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.HealthCheck": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/handlers.HealthStatus"
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handlers.HealthCheck"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/handlers.HealthStats"
                },
                "status": {
                    "$ref": "#/definitions/handlers.HealthStatus"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "handlers.HealthStats": {
            "type": "object",
            "properties": {
                "active_terminals": {
                    "type": "integer"
                },
                "goroutines": {
                    "type": "integer"
                },
                "heap_alloc_mb": {
                    "type": "integer"
                },
                "heap_sys_mb": {
                    "type": "integer"
                },
                "num_gc": {
                    "type": "integer"
                }
            }
        },
        "handlers.HealthStatus": {
            "type": "string",
            "enum": [
                "healthy",
                "degraded",
                "unhealthy"
            ],
            "x-enum-varnames": [
                "HealthStatusHealthy",
                "HealthStatusDegraded",
                "HealthStatusUnhealthy"
            ]
        },
        "handlers.HostInfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "claude_dir": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/handlers.HostStats"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.HostStats": {
            "type": "object",
            "properties": {
                "active_terminals": {
                    "type": "integer"
                },
                "total_projects": {
                    "type": "integer"
                },
                "total_sessions": {
                    "type": "integer"
                }
            }
        },
        "services.ClaudeSession": {
            "type": "object",
            "properties": {
                "assistant_messages": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "first_message": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_path": {
                    "type": "string"
                },
                "real_path": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "user_messages": {
                    "type": "integer"
                }
            }
        },
        "services.ClaudeStateSnapshot": {
            "type": "object",
            "properties": {
                "archived_at": {
                    "type": "string"
                },
                "assistant_messages": {
                    "type": "integer"
                },
                "error": {
                    "$ref": "#/definitions/services.TerminalError"
                },
                "message_count": {
                    "type": "integer"
                },
                "pause_count": {
                    "type": "integer"
                },
                "paused_at": {
                    "type": "string"
                },
                "resume_count": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/services.TerminalState"
                },
                "stopped_at": {
                    "type": "string"
                },
                "user_messages": {
                    "type": "integer"
                }
            }
        },
        "services.DailyActivity": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "messages": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                }
            }
        },
        "services.GlobalAnalytics": {
            "type": "object",
            "properties": {
                "active_days": {
                    "type": "integer"
                },
                "cached_until": {
                    "type": "string"
                },
                "daily_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.DailyActivity"
                    }
                },
                "empty_sessions": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "string"
                },
                "projects_summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ProjectSummary"
                    }
                },
                "total_assistant_messages": {
                    "type": "integer"
                },
                "total_messages": {
                    "type": "integer"
                },
                "total_projects": {
                    "type": "integer"
                },
                "total_sessions": {
                    "type": "integer"
                },
                "total_size_bytes": {
                    "type": "integer"
                },
                "total_user_messages": {
                    "type": "integer"
                }
            }
        },
        "services.MoveSessionResult": {
            "type": "object",
            "properties": {
                "new_project_path": {
                    "type": "string"
                },
                "new_real_path": {
                    "type": "string"
                },
                "old_project_path": {
                    "type": "string"
                },
                "old_real_path": {
                    "type": "string"
                },
                "paths_replaced": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "services.ProjectAnalytics": {
            "type": "object",
            "properties": {
                "cached_until": {
                    "type": "string"
                },
                "daily_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.DailyActivity"
                    }
                },
                "empty_sessions": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "real_path": {
                    "type": "string"
                },
                "top_days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.DailyActivity"
                    }
                },
                "total_assistant_messages": {
                    "type": "integer"
                },
                "total_messages": {
                    "type": "integer"
                },
                "total_sessions": {
                    "type": "integer"
                },
                "total_size_bytes": {
                    "type": "integer"
                },
                "total_user_messages": {
                    "type": "integer"
                }
            }
        },
        "services.ProjectSummary": {
            "type": "object",
            "properties": {
                "assistant_messages": {
                    "type": "integer"
                },
                "empty_sessions": {
                    "type": "integer"
                },
                "last_activity": {
                    "type": "string"
                },
                "messages": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "real_path": {
                    "type": "string"
                },
                "sessions": {
                    "type": "integer"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "user_messages": {
                    "type": "integer"
                }
            }
        },
        "services.TerminalConfig": {
            "type": "object",
            "properties": {
                "additional_dirs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "allowed_tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "string"
                },
                "continue": {
                    "type": "boolean"
                },
                "dangerously_skip": {
                    "type": "boolean"
                },
                "disallowed_tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission_mode": {
                    "type": "string"
                },
                "resume": {
                    "type": "boolean"
                },
                "system_prompt": {
                    "type": "string"
                },
                "type": {
                    "description": "\"claude\" o \"terminal\"",
                    "type": "string"
                },
                "work_dir": {
                    "type": "string"
                }
            }
        },
        "services.TerminalError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "services.TerminalInfo": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "can_resume": {
                    "type": "boolean"
                },
                "claude_state": {
                    "description": "Solo para tipo claude",
                    "allOf": [
                        {
                            "$ref": "#/definitions/services.ClaudeStateSnapshot"
                        }
                    ]
                },
                "clients": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_access_at": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "work_dir": {
                    "type": "string"
                }
            }
        },
        "services.TerminalState": {
            "type": "string",
            "enum": [
                "created",
                "starting",
                "active",
                "paused",
                "stopped",
                "archived",
                "error"
            ],
            "x-enum-varnames": [
                "TerminalStateCreated",
                "TerminalStateStarting",
                "TerminalStateActive",
                "TerminalStatePaused",
                "TerminalStateStopped",
                "TerminalStateArchived",
                "TerminalStateError"
            ]
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.1.0",
	Host:             "localhost:9090",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Claude Monitor API",
	Description:      "API para monitorear y gestionar sesiones de Claude Code, terminales PTY, jobs y analytics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
